import { PortfolioData } from './types'
import profilePhoto from '@/assets/images/PHOTO-PS-MD_ABDULLAH_FARUQUE.JPG'

// Visitors keep a copy of this data in localStorage. Bump the version whenever
// this file changes so returning visitors get the update (App.tsx replaces any
// stored copy with an older version).
export const PORTFOLIO_DATA_VERSION = 3

export const initialPortfolioData: PortfolioData = {
  name: 'MD Abdullah Faruque',
  title: 'Senior Full Stack .NET Developer',
  tagline: 'Building scalable, cloud-native applications with modern technologies',
  photoUrl: profilePhoto,
  contact: {
    email: 'mabdullahfaruque@gmail.com',
    linkedin: 'https://www.linkedin.com/in/mdabdullahfaruque',
    location: 'Kuala Lumpur, Malaysia',
    phone: '+60175165646',
    github: 'https://github.com/mdabdullahfaruque',
  },
  summary:
    'Senior Full Stack .NET Developer with 6+ years of experience building cloud-native systems in C#, .NET, Azure and AWS. Currently leading development of a production multi-tenant SaaS marketplace, covering payments, recurring billing, SSO and Microsoft Marketplace integration. Skilled in Blazor WebAssembly, Angular, React and jQuery, and in agentic AI development with Claude Code, GitHub Copilot, Cursor and MCP. Experienced team lead focused on building scalable, high-performance systems.',
  aboutMe:
    'Passionate software engineer with a proven track record of delivering enterprise-scale applications across multiple industries including fintech, e-commerce, and technology. I thrive in collaborative environments and am committed to writing clean, maintainable code while staying at the forefront of technological innovation.',
  experiences: [
    {
      id: '1',
      title: 'Senior Full Stack Developer',
      company: 'Aventra Group Sdn. Bhd.',
      location: 'Kuala Lumpur, Malaysia',
      startDate: 'January 2026',
      endDate: 'Present',
      description: 'Multinational technology company delivering innovative software solutions',
      companyType: 'Technology Company',
      achievements: [
        'Leading the team building AG ONE, a million-dollar multi-tenant SaaS marketplace; own architecture, estimation, delivery reporting and developer performance reviews',
        'Managing the team and driving rapid, AI-driven software development with Claude Code, GitHub Copilot and MCP',
        'Built multi-gateway payments (Stripe, 2C2P) and a Quartz.NET recurring billing engine',
        'Integrated Microsoft Marketplace SaaS fulfillment and Pax8 Microsoft 365 licensing',
        'Designed Entra ID SSO and 3-level RBAC for multi-tenant access control',
        'Building AI features with RAG and sentiment analysis',
      ],
      technologies: [
        '.NET 8',
        'C#',
        'Blazor WebAssembly',
        'MudBlazor',
        'ASP.NET Core Web API',
        'Entity Framework Core',
        'SQL Server',
        'Azure',
        'Service Bus',
        'Entra ID',
        'Microsoft Graph',
        'Stripe',
        '2C2P',
        'Quartz.NET',
        'Azure DevOps',
        'RAG',
      ],
    },
    {
      id: '2',
      title: 'Full Stack Developer',
      company: "Domino's Pizza Enterprises",
      location: 'Kuala Lumpur, Malaysia',
      startDate: 'January 2025',
      endDate: 'December 2025',
      description: "Australia-based, largest Domino's franchise worldwide",
      companyType: 'Food & Beverage',
      achievements: [
        'Migrated global web platforms from .NET Framework 4.8 to .NET 8, ensuring stability for millions of users across 12 markets',
        'Built and deployed scalable applications that enhanced customer experience in Europe, Australia, and Southeast Asia',
        'Collaborated with a multinational agile team, improving release cycles, system reliability, and cross-market consistency',
        'Leveraged AI tools (GitHub Copilot, MCP Servers) and automated E2E testing with Playwright',
      ],
      technologies: ['.NET 8', 'C#', 'Azure', 'CI/CD', 'Playwright', 'Agile'],
    },
    {
      id: '3',
      title: 'Software Engineer',
      company: 'Public Bank',
      location: 'Bangi, Malaysia',
      startDate: 'August 2024',
      endDate: 'December 2024',
      description: 'Leading banking and financial services organization in Malaysia',
      companyType: 'Financial Services',
      achievements: [
        'Led legacy banking software migration to .NET 8, implementing modular monolith architectures and seamless data integration with Microsoft SQL Server',
        'Developed and enhanced high-performance on-premise banking applications serving millions of users using .NET Framework MVC, C#, jQuery, and SQL Server',
      ],
      technologies: ['.NET 8', '.NET Framework MVC', 'C#', 'SQL Server', 'jQuery', 'Modular Monolith Architecture'],
    },
    {
      id: '4',
      title: 'Software Engineer',
      company: 'Kaz Software',
      location: 'Dhaka, Bangladesh',
      startDate: 'March 2023',
      endDate: 'July 2024',
      description: 'Software development company with a focus on innovative IT solutions',
      companyType: 'Software Company',
      achievements: [
        'Led development of .NET 8/6, Angular, and React applications, implementing scalable WebAPI and MVC architectures',
        'Designed and developed cross-platform real-time communication solutions integrating SignalR, AWS WebSocket, and Twilio SDK',
        'Implemented microservices architecture patterns',
        'Mentored junior developers on best practices',
      ],
      technologies: [
        '.NET 8',
        '.NET 6',
        'Angular',
        'React',
        'WebAPI',
        'MVC',
        'SignalR',
        'AWS WebSocket',
        'Twilio SDK',
        'Amazon Cognito',
      ],
    },
    {
      id: '5',
      title: 'Associate Software Engineer',
      company: 'Kaz Software',
      location: 'Dhaka, Bangladesh',
      startDate: 'July 2020',
      endDate: 'February 2023',
      description: 'Software development company with a focus on innovative IT solutions',
      companyType: 'Software Company',
      achievements: [
        'Developed serverless applications using AWS API Gateway and Lambda Functions with C#, .NET 6/.NET Core 3.1',
        'Implemented hybrid database solutions by combining EF Core code-first with MySQL and AWS DynamoDB to support diverse storage needs',
        'Orchestrated event-driven workflows with AWS EventBridge and Step Functions, improving automation and system scalability',
      ],
      technologies: [
        'AWS Lambda',
        'API Gateway',
        'DynamoDB',
        'EventBridge',
        'Step Functions',
        '.NET 6',
        '.NET Core 3.1',
        'EF Core',
        'MySQL',
      ],
    },
  ],
  education: [
    {
      id: '1',
      degree: 'B.Sc (Engineering) in Computer Science and Engineering',
      institution: 'Comilla University',
      location: 'Cumilla, Bangladesh',
      startDate: 'March 2015',
      endDate: 'June 2020',
      description:
        'Strong foundation in computer science fundamentals with focus on software engineering principles and projects in web development and cloud computing.',
    },
  ],
  skills: {
    backend: [
      { name: 'C#', proficiency: 95, yearsOfExperience: 6 },
      { name: '.NET 8/10', proficiency: 90, yearsOfExperience: 3 },
      { name: '.NET Core', proficiency: 92, yearsOfExperience: 5 },
      { name: '.NET Framework', proficiency: 88, yearsOfExperience: 6 },
      { name: 'ASP.NET MVC', proficiency: 90, yearsOfExperience: 6 },
      { name: 'Web API', proficiency: 95, yearsOfExperience: 6 },
      { name: 'Entity Framework Core', proficiency: 90, yearsOfExperience: 5 },
      { name: 'Quartz.NET', proficiency: 80, yearsOfExperience: 1 },
      { name: 'Stripe', proficiency: 80, yearsOfExperience: 1 },
      { name: '2C2P', proficiency: 78, yearsOfExperience: 1 },
    ],
    frontend: [
      { name: 'Angular', proficiency: 85, yearsOfExperience: 4 },
      { name: 'React', proficiency: 88, yearsOfExperience: 4 },
      { name: 'Blazor WebAssembly', proficiency: 80, yearsOfExperience: 2 },
      { name: 'jQuery', proficiency: 85, yearsOfExperience: 6 },
      { name: 'TypeScript', proficiency: 90, yearsOfExperience: 5 },
      { name: 'HTML5', proficiency: 95, yearsOfExperience: 6 },
      { name: 'CSS3', proficiency: 90, yearsOfExperience: 6 },
      { name: 'MudBlazor', proficiency: 80, yearsOfExperience: 1 },
    ],
    cloud: [
      { name: 'AWS Lambda', proficiency: 85, yearsOfExperience: 4 },
      { name: 'API Gateway', proficiency: 80, yearsOfExperience: 4 },
      { name: 'DynamoDB', proficiency: 82, yearsOfExperience: 4 },
      { name: 'EventBridge', proficiency: 75, yearsOfExperience: 3 },
      { name: 'Cognito', proficiency: 78, yearsOfExperience: 3 },
      { name: 'S3', proficiency: 88, yearsOfExperience: 4 },
      { name: 'Azure App Services', proficiency: 85, yearsOfExperience: 3 },
      { name: 'Azure Functions', proficiency: 82, yearsOfExperience: 3 },
      { name: 'Azure DevOps', proficiency: 80, yearsOfExperience: 3 },
      { name: 'App Insights', proficiency: 75, yearsOfExperience: 2 },
      { name: 'Entra ID', proficiency: 82, yearsOfExperience: 1 },
      { name: 'Azure Service Bus', proficiency: 78, yearsOfExperience: 1 },
    ],
    databases: [
      { name: 'SQL Server', proficiency: 92, yearsOfExperience: 6 },
      { name: 'MySQL', proficiency: 85, yearsOfExperience: 5 },
      { name: 'PostgreSQL', proficiency: 80, yearsOfExperience: 3 },
      { name: 'DynamoDB', proficiency: 82, yearsOfExperience: 4 },
      { name: 'Redis Cache', proficiency: 78, yearsOfExperience: 3 },
    ],
    testing: [
      { name: 'nUnit', proficiency: 85, yearsOfExperience: 5 },
      { name: 'xUnit', proficiency: 85, yearsOfExperience: 5 },
      { name: 'Playwright', proficiency: 80, yearsOfExperience: 2 },
      { name: 'Docker', proficiency: 75, yearsOfExperience: 3 },
      { name: 'Git', proficiency: 92, yearsOfExperience: 6 },
      { name: 'Azure DevOps', proficiency: 80, yearsOfExperience: 3 },
      { name: 'CI/CD', proficiency: 82, yearsOfExperience: 4 },
    ],
    tools: [
      { name: 'Visual Studio', proficiency: 95, yearsOfExperience: 6 },
      { name: 'SEO', proficiency: 75, yearsOfExperience: 1 },
      { name: 'GEO (AI Search Optimization)', proficiency: 70, yearsOfExperience: 1 },
      { name: 'Google Analytics 4 (GA4)', proficiency: 72, yearsOfExperience: 1 },
      { name: 'VS Code', proficiency: 92, yearsOfExperience: 6 },
      { name: 'GitHub Copilot', proficiency: 88, yearsOfExperience: 2 },
      { name: 'Cursor', proficiency: 85, yearsOfExperience: 1 },
    ],
    cms: [
      { name: 'Umbraco CMS', proficiency: 82, yearsOfExperience: 2 },
    ],
    ai: [
      { name: 'GitHub Copilot', proficiency: 88, yearsOfExperience: 2 },
      { name: 'Cursor', proficiency: 85, yearsOfExperience: 1 },
      { name: 'Claude', proficiency: 80, yearsOfExperience: 1 },
      { name: 'RAG', proficiency: 75, yearsOfExperience: 1 },
      { name: 'Sentiment Analysis', proficiency: 72, yearsOfExperience: 1 },
      { name: 'MCP Server', proficiency: 78, yearsOfExperience: 1 },
      { name: 'Agent Instructions', proficiency: 75, yearsOfExperience: 1 },
      { name: 'Agentic Workflows', proficiency: 75, yearsOfExperience: 1 },
      { name: 'Claude Code', proficiency: 88, yearsOfExperience: 1 },
    ],
  },
  projects: [
    {
      id: 'ag-one',
      name: 'AG ONE',
      url: 'https://www.ag-one.aventragroup.com/',
      description:
        'Production multi-tenant SaaS marketplace where companies browse a product catalog, buy subscriptions and launch into AG ONE products (Work, Learn, Safe, Hire).',
      status: 'Live',
      technologies: ['.NET 8', 'Blazor WebAssembly', 'SQL Server', 'Azure', 'Entra ID', 'Stripe', '2C2P', 'Quartz.NET'],
      features: [
        'Lead developer and top contributor with 250+ merged pull requests',
        'Provider-agnostic payment layer with currency-based routing across Stripe and 2C2P',
        'Recurring billing with dunning and idempotent retries',
        'Microsoft Marketplace SaaS fulfillment and Pax8 Microsoft 365 licensing',
        'Entra ID SSO and 3-level RBAC across tenants',
      ],
    },
    {
      id: '1',
      name: 'MyPropertyMart',
      url: 'https://mypropertymart.com/',
      description:
        'All-in-one platform connecting buyers, sellers, housing construction companies, and trusted materials suppliers.',
      status: 'Live',
      market: 'Bangladesh & Malaysia',
      technologies: ['.NET', 'Angular', 'SQL Server', 'Azure'],
      features: [
        'Property listing and search',
        'Construction company directory',
        'Materials supplier marketplace',
        'Multi-language support',
      ],
    },
    {
      id: '2',
      name: 'SasthoSeba',
      url: 'https://sasthoseba.com/',
      description:
        'A comprehensive healthcare solution currently focusing on digital prescription writing, patient management, and chamber management for doctors.',
      status: 'Live',
      market: 'Bangladesh',
      technologies: ['.NET', 'React', 'SQL Server', 'Azure'],
      features: [
        'Digital prescription writing',
        'Patient management system',
        'Doctor chamber management',
        'Appointment scheduling',
        'Future: Clinics, Diagnostic Centers, Pharmacies, Telemedicine',
      ],
    },
    {
      id: 'dominos-migration',
      name: "Domino's Global Web Platform Migration",
      url: 'https://www.dominos.com.au/',
      description:
        'Customer-facing web platforms serving millions of users across 12 markets in Europe, Australia and Southeast Asia, migrated from .NET Framework 4.8 to .NET 8.',
      status: 'Live',
      market: 'Europe, Australia & Southeast Asia',
      technologies: ['.NET 8', '.NET Framework 4.8', 'C#', 'Azure', 'CI/CD', 'Playwright'],
      features: [
        'Migration from .NET Framework 4.8 to .NET 8',
        'Automated Playwright end-to-end tests protecting cross-market releases',
        'Stable releases for millions of users in 12 markets',
      ],
    },
    {
      id: 'web-evv',
      name: 'Web EVV',
      url: '',
      description:
        'Web platform with a mobile app that simplifies electronic visit verification (EVV) for home care agencies, integrating scheduling, documentation and billing in collaboration with health insurers.',
      status: 'Jan 2023 – Jul 2024',
      technologies: ['C#', 'Amazon DynamoDB'],
    },
    {
      id: 'gateway-to-access',
      name: 'Gateway to Access',
      url: '',
      description:
        'Web, desktop and mobile apps where doctors and lawyers work with interpreters to talk to patients and clients in their native language, remotely (audio/video) or face to face, in real time or by scheduled meeting.',
      status: 'May 2021 – Jan 2023',
      technologies: ['C#', '.NET 6', '.NET Core', 'AWS', 'React'],
      features: [
        'R&D and core features across multiple server-side projects in C# (.NET 6)',
        'Configured and managed AWS cloud services and designed database schemas',
        'Developed the web UI in React',
      ],
    },
  ],
  certifications: [
    {
      id: '1',
      name: 'Introduction to Model Context Protocol',
      issuer: 'Anthropic',
      date: 'November 2025',
      credentialUrl: 'https://verify.skilljar.com/c/imdn3ipo5r6b',
    },
  ],
  languages: [
    { name: 'English', proficiency: 'Professional Working Proficiency' },
    { name: 'Bengali', proficiency: 'Native' },
  ],
  stats: [
    { id: '1', label: 'Years Experience', value: '6+', icon: 'briefcase', translationKey: 'yearsExperience' },
    { id: '2', label: 'Projects Completed', value: '15+', icon: 'code', translationKey: 'projectsCompleted' },
    { id: '3', label: 'Live Products', value: '2', icon: 'rocket', translationKey: 'liveProducts' },
    { id: '4', label: 'Technologies', value: '30+', icon: 'stack', translationKey: 'technologies' },
  ],
  heroSkills: [
    'C#',
    '.NET 8/10',
    '.NET Core',
    'Angular',
    'React',
    'Azure',
    'AWS Lambda',
  ],
  highlights: [
    'Leading the team building AG ONE, a million-dollar software marketplace',
    'Driving rapid, AI-driven software development while managing the team',
    'Led migration of global web platforms serving millions of users across 12+ markets',
    'Migrated critical systems to .NET 8, improving performance by 40%',
    'Supported 12+ markets with multi-language, multi-currency systems designed for 99.9% uptime',
    'Mentored junior developers and led technical teams in architecture decisions',
  ],
}
