import { PortfolioData } from './types'
import profilePhoto from '@/assets/images/PHOTO-PS-MD_ABDULLAH_FARUQUE.JPG'

export const initialPortfolioData: PortfolioData = {
  name: 'MD Abdullah Faruque',
  title: 'Senior Full Stack Developer',
  tagline: 'Building scalable, cloud-native applications with modern technologies',
  photoUrl: profilePhoto,
  contact: {
    email: 'mabdullahfaruque@gmail.com',
    linkedin: 'https://www.linkedin.com/in/mdabdullahfaruque',
    location: 'Kuala Lumpur, Malaysia',
    phone: '+60175165646',
    github: 'https://github.com/mdabdullahfaruque',
  },
  summary:
    'Senior Full Stack .NET Developer with 6 years of experience in C#, .NET, and cloud architecture using AWS and Azure. Skilled in Angular, React, Blazor WebAssembly, and jQuery. Proficient in full-stack development, cloud-native applications, and AI-driven development. Experienced team lead focused on building scalable, high-performance systems.',
  aboutMe:
    'Passionate software engineer with a proven track record of delivering enterprise-scale applications across multiple industries including fintech, e-commerce, and technology. I thrive in collaborative environments and am committed to writing clean, maintainable code while staying at the forefront of technological innovation.',
  experiences: [
    {
      id: '1',
      title: 'Senior Full Stack Developer',
      company: 'Aventra Group Sdn. Bhd.',
      location: 'Kuala Lumpur, Malaysia',
      startDate: 'January 2026',
      endDate: 'Present',
      description: 'Multinational Technology company delivering innovative software solutions',
      companyType: 'Technology Company',
      achievements: [
        'Leading team to develop internal products, managing end-to-end development process and ensuring timely delivery',
        'Architecting and implementing AI-driven features including sentiment analysis and RAG (Retrieval-Augmented Generation)',
        'Leveraging agentic AI tools (GitHub Copilot, Cursor, Claude) with MCP server, instructions, agent skills, and hooks',
        'Driving modern development practices across the team',
      ],
      technologies: ['.NET', 'SQL Server', 'Azure', 'Blazor WebAssembly', 'Web API', 'RAG', 'Sentiment Analysis'],
    },
    {
      id: '2',
      title: 'Full Stack Developer',
      company: "Domino's Pizza Enterprises",
      location: 'Kuala Lumpur, Malaysia',
      startDate: 'January 2025',
      endDate: 'December 2025',
      description: "Australia-based, largest Domino's franchise worldwide",
      companyType: 'Food & Beverage',
      achievements: [
        'Migrated global web platforms from .NET Framework 4.8 to .NET 8, ensuring stability for millions of users across 12 markets',
        'Built and deployed scalable applications that enhanced customer experience in Europe, Australia, and Southeast Asia',
        'Collaborated with a multinational agile team, improving release cycles, system reliability, and cross-market consistency',
        'Leveraged AI tools (GitHub Copilot, MCP Servers) and automated E2E testing with Playwright',
      ],
      technologies: ['.NET 8', 'Umbraco', 'C#', 'Azure', 'MCP Servers', 'Playwright', 'Agile'],
    },
    {
      id: '3',
      title: 'Software Engineer',
      company: 'Public Bank',
      location: 'Bangi, Malaysia',
      startDate: 'August 2024',
      endDate: 'December 2024',
      description: 'Leading banking and financial services organization in Malaysia',
      companyType: 'Financial Services',
      achievements: [
        'Led legacy banking software migration to .NET 8, implementing modular monolith architectures and seamless data integration with Microsoft SQL Server',
        'Developed and enhanced high-performance on-premise banking applications serving millions of users using .NET Framework MVC, C#, jQuery, and SQL Server',
      ],
      technologies: ['.NET 8', '.NET Framework MVC', 'C#', 'SQL Server', 'jQuery'],
    },
    {
      id: '4',
      title: 'Software Engineer',
      company: 'Kaz Software',
      location: 'Dhaka, Bangladesh',
      startDate: 'July 2020',
      endDate: 'July 2024',
      description: 'Software development company with a focus on innovative IT solutions',
      companyType: 'Software Company',
      achievements: [
        'Led development of .NET 8/6, Angular, and React applications with scalable WebAPI, MVC, and real-time communication via SignalR, AWS WebSocket, and Twilio SDK',
        'Developed serverless applications using AWS Lambda, API Gateway, EventBridge, and Step Functions',
        'Implemented hybrid database solutions combining EF Core with MySQL and AWS DynamoDB',
      ],
      technologies: [
        '.NET 8/6',
        '.NET Core 3.1',
        'Angular',
        'React',
        'WebAPI',
        'SignalR',
        'AWS Lambda',
        'DynamoDB',
        'EventBridge',
        'EF Core',
      ],
    },
  ],
  education: [
    {
      id: '1',
      degree: 'B.Sc (Engineering) in Computer Science and Engineering',
      institution: 'Comilla University',
      location: 'Cumilla, Bangladesh',
      startDate: 'March 2015',
      endDate: 'June 2020',
      description:
        'Strong foundation in computer science fundamentals with focus on software engineering principles and projects in web development and cloud computing.',
    },
  ],
  skills: {
    backend: [
      { name: 'C#', proficiency: 95, yearsOfExperience: 6 },
      { name: '.NET 8/10', proficiency: 90, yearsOfExperience: 3 },
      { name: '.NET Core', proficiency: 92, yearsOfExperience: 5 },
      { name: '.NET Framework', proficiency: 88, yearsOfExperience: 6 },
      { name: 'ASP.NET MVC', proficiency: 90, yearsOfExperience: 6 },
      { name: 'Web API', proficiency: 95, yearsOfExperience: 6 },
      { name: 'Entity Framework Core', proficiency: 90, yearsOfExperience: 5 },
    ],
    frontend: [
      { name: 'Angular', proficiency: 85, yearsOfExperience: 4 },
      { name: 'React', proficiency: 88, yearsOfExperience: 4 },
      { name: 'Blazor WebAssembly', proficiency: 80, yearsOfExperience: 2 },
      { name: 'jQuery', proficiency: 85, yearsOfExperience: 6 },
      { name: 'TypeScript', proficiency: 90, yearsOfExperience: 5 },
      { name: 'HTML5', proficiency: 95, yearsOfExperience: 6 },
      { name: 'CSS3', proficiency: 90, yearsOfExperience: 6 },
    ],
    cloud: [
      { name: 'AWS Lambda', proficiency: 85, yearsOfExperience: 4 },
      { name: 'API Gateway', proficiency: 80, yearsOfExperience: 4 },
      { name: 'DynamoDB', proficiency: 82, yearsOfExperience: 4 },
      { name: 'EventBridge', proficiency: 75, yearsOfExperience: 3 },
      { name: 'Cognito', proficiency: 78, yearsOfExperience: 3 },
      { name: 'S3', proficiency: 88, yearsOfExperience: 4 },
      { name: 'Azure App Services', proficiency: 85, yearsOfExperience: 3 },
      { name: 'Azure Functions', proficiency: 82, yearsOfExperience: 3 },
      { name: 'Azure DevOps', proficiency: 80, yearsOfExperience: 3 },
      { name: 'App Insights', proficiency: 75, yearsOfExperience: 2 },
    ],
    databases: [
      { name: 'SQL Server', proficiency: 92, yearsOfExperience: 6 },
      { name: 'MySQL', proficiency: 85, yearsOfExperience: 5 },
      { name: 'PostgreSQL', proficiency: 80, yearsOfExperience: 3 },
      { name: 'DynamoDB', proficiency: 82, yearsOfExperience: 4 },
      { name: 'Redis Cache', proficiency: 78, yearsOfExperience: 3 },
    ],
    testing: [
      { name: 'nUnit', proficiency: 85, yearsOfExperience: 5 },
      { name: 'xUnit', proficiency: 85, yearsOfExperience: 5 },
      { name: 'Playwright', proficiency: 80, yearsOfExperience: 2 },
      { name: 'Docker', proficiency: 75, yearsOfExperience: 3 },
      { name: 'Git', proficiency: 92, yearsOfExperience: 6 },
      { name: 'Azure DevOps', proficiency: 80, yearsOfExperience: 3 },
      { name: 'CI/CD', proficiency: 82, yearsOfExperience: 4 },
    ],
    tools: [
      { name: 'Visual Studio', proficiency: 95, yearsOfExperience: 6 },
      { name: 'VS Code', proficiency: 92, yearsOfExperience: 6 },
      { name: 'GitHub Copilot', proficiency: 88, yearsOfExperience: 2 },
      { name: 'Cursor', proficiency: 85, yearsOfExperience: 1 },
    ],
    cms: [
      { name: 'Umbraco CMS', proficiency: 82, yearsOfExperience: 2 },
    ],
    ai: [
      { name: 'GitHub Copilot', proficiency: 88, yearsOfExperience: 2 },
      { name: 'Cursor', proficiency: 85, yearsOfExperience: 1 },
      { name: 'Claude', proficiency: 80, yearsOfExperience: 1 },
      { name: 'RAG', proficiency: 75, yearsOfExperience: 1 },
      { name: 'Sentiment Analysis', proficiency: 72, yearsOfExperience: 1 },
      { name: 'MCP Server', proficiency: 78, yearsOfExperience: 1 },
      { name: 'Agent Instructions', proficiency: 75, yearsOfExperience: 1 },
      { name: 'Agentic Workflows', proficiency: 75, yearsOfExperience: 1 },
    ],
  },
  projects: [
    {
      id: '1',
      name: 'MyPropertyMart',
      url: 'https://mypropertymart.com/',
      description:
        'All-in-one platform connecting buyers, sellers, housing construction companies, and trusted materials suppliers.',
      status: 'Live',
      market: 'Bangladesh & Malaysia',
      technologies: ['.NET', 'Angular', 'SQL Server', 'Azure'],
      features: [
        'Property listing and search',
        'Construction company directory',
        'Materials supplier marketplace',
        'Multi-language support',
      ],
    },
    {
      id: '2',
      name: 'SasthoSeba',
      url: 'https://sasthoseba.com/',
      description:
        'A comprehensive healthcare solution currently focusing on digital prescription writing, patient management, and chamber management for doctors.',
      status: 'Live',
      market: 'Bangladesh',
      technologies: ['.NET', 'React', 'SQL Server', 'Azure'],
      features: [
        'Digital prescription writing',
        'Patient management system',
        'Doctor chamber management',
        'Appointment scheduling',
        'Future: Clinics, Diagnostic Centers, Pharmacies, Telemedicine',
      ],
    },
  ],
  certifications: [
    {
      id: '1',
      name: 'Introduction to Model Context Protocol',
      issuer: 'Anthropic',
      date: 'November 2025',
      credentialUrl: 'https://verify.skilljar.com/c/imdn3ipo5r6b',
    },
  ],
  languages: [
    { name: 'English', proficiency: 'Professional Working Proficiency' },
    { name: 'Bengali', proficiency: 'Native' },
  ],
  stats: [
    { id: '1', label: 'Years Experience', value: '6+', icon: 'briefcase', translationKey: 'yearsExperience' },
    { id: '2', label: 'Projects Completed', value: '15+', icon: 'code', translationKey: 'projectsCompleted' },
    { id: '3', label: 'Live Products', value: '2', icon: 'rocket', translationKey: 'liveProducts' },
    { id: '4', label: 'Technologies', value: '30+', icon: 'stack', translationKey: 'technologies' },
  ],
  heroSkills: [
    'C#',
    '.NET 8/10',
    '.NET Core',
    'Angular',
    'React',
    'Azure',
    'AWS Lambda',
  ],
  highlights: [
    'Led migration of global web platforms serving millions of users across 12+ markets',
    'Architected and implemented AI-driven features including RAG and Sentiment Analysis',
    'Developed serverless applications using AWS Lambda, reducing infrastructure costs by 30%',
    'Optimized database queries reducing response time by 60%',
    'Implemented secure banking applications with 99.9% uptime',
    'Mentored junior developers and led technical teams in architecture decisions'
  ],
}
